name: uxarray_build
channels:
  - conda-forge
  - UXARRAY
dependencies:
  - python
  - cftime
  - dask
  - distributed
  - eofs
  - netcdf4
  - numpy
  - pytest
  - pytest-cov
  - pip
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/xarray-contrib/cf-xarray.git
