name: Feature Request
description: Request new or improved functionality or changes to existing UXarray functionality
title: "🌎[ENH]: <Please write a comprehensive title for the feature request>"
labels: bug

body:
- type: markdown
  attributes:
    value: >
      TODO
   
- type: textarea
  attributes:
    label: "Proposed new feature or change:"
  validations:
    required: true


