name: uxarray_build
channels:
  - conda-forge
dependencies:
  - dask
  - netcdf4
  - numba
  - numpy
  - pathlib
  - pre_commit
  - pytest
  - pytest-cov
  - scipy
  - xarray
  - shapely
  - spatialpandas
  - matplotlib
  - pip:
    - antimeridian+https://github.com/gadomski/antimeridian.git
