name: uxarray_build
channels:
  - conda-forge
dependencies:
  - dask
  - matplotlib-base
  - netcdf4
  - numba
  - numpy
  - pathlib
  - pre_commit
  - pytest
  - pytest-cov
  - scikit-learn
  - scipy
  - shapely
  - spatialpandas
  - xarray
  - pip:
    - antimeridian
